export const NOTIFICATION_TYPES = {
  TASK: 'TASK',
  LEAVE: 'LEAVE',
  TIMESHEET: 'TIMESHEET',
  ANNOUNCEMENT: 'ANNOUNCEMENT'
};

export const ANNOUNCEMENT_CATEGORIES = {
  HOLIDAY: 'HOLIDAY',
  EVENT: 'EVENT',
  POLICY: 'POLICY',
  GENERAL: 'GENERAL'
};

export const ANNOUNCEMENT_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED'
};

